steps:
  - label: "Do something"
    command: "git fetch origin --tags"
  - label: ":gradle: Gradle build"
    agents:
      environment: 'non-prod'
    artifact_paths:
      - "**/*.apk"
      - "**/*.aar"
    plugins:
      - docker#v3.2.0:
          image: "620422829213.dkr.ecr.us-east-1.amazonaws.com/ttm-mobile/android-build-image:28.0.3"
          command:
            - "git fetch origin --tags"
            - "git describe --tags --abbrev=0 origin/master"
          always-pull: true
          environment:
            - "REPO_NAME=maine-custom-controls"
            - "ORG_GRADLE_PROJECT_branch=$BUILDKITE_BRANCH"
            - "ORG_GRADLE_PROJECT_buildNumber=${BUILDKITE_BUILD_NUMBER}"
